LeagueStore.Uitwerking/Controllers/BundleController.cs
using LeagueStore.Models;
using LeagueStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeagueStore.Controllers
{
    public class BundleController : Controller
    {
        // GET: Bundle
        public ActionResult Index()
        {

            using (var context = new MyContext())
            {

                List<Bundle> bundles = context.Bundles
                    .Include("Products").ToList();

                return View(bundles);
            } 
        }

        public ActionResult Create()
        {
            using (var context = new MyContext())
            {
                var bundle = new Bundle();
                bundle.BannerUrl = "~/Content/img/default.jpg";
                var products = context.Products.ToList();
                return View(new BundleVM { Bundle = bundle, Products = products });
            }
        }

        [HttpPost]
        public ActionResult Create(BundleVM bundleVM)
        {
            SaveBundle(bundleVM);
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int bundleId)
        {
            using (var context = new MyContext())
            {

                Bundle bundle = context.Bundles.Find(bundleId);
                var products = context.Products.ToList();
                return View(new BundleVM { Bundle = bundle, Products = products });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BundleVM bundleVM)
        {
            SaveBundle(bundleVM);
            return RedirectToAction("Index");
        }

        private void SaveBundle(BundleVM bundleVM)
        {
            Bundle bundle;
            using (var context = new MyContext())
            {
                if(bundleVM.Bundle.Id == 0){
                    bundle = new Bundle();
                    context.Bundles.Add(bundle);
                }
                else{
                    bundle = context.Bundles.Include("Products")
                        .First(b => b.Id == bundleVM.Bundle.Id);
                }

                bundle.Name = bundleVM.Bundle.Name;
                bundle.Description = bundleVM.Bundle.Description;
                bundle.RiotPoints = bundleVM.Bundle.RiotPoints;
                bundle.BannerUrl = bundleVM.Bundle.BannerUrl;
                bundle.Products = bundleVM.ProductIds.Select(pi => context.Products.Find(pi)).ToList();
                context.SaveChanges();
            }
        }
    }
}

LeagueStore.Uitwerking/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueStore.Models;

namespace LeagueStore.Controllers
{
    public class ProductController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Product
        public ActionResult Index()
        {
            var model = db.Products.ToList();

            return View(model);
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Gold,ItemUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Gold,ItemUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeagueStore.Uitwerking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>League Store</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
 
</head>
<body>
    <div class="brand">League Store</div>
    <div class="address-bar">Project and property of Avans Hogeschool</div>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li>@Html.ActionLink("News", "News", "Home")</li>
                    <li>@Html.ActionLink("Webshop", "Index", "Product")</li>
                    <li>@Html.ActionLink("Bundles", "Index", "Bundle")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("scripts", required: false)

    <script>
        $('.carousel').carousel({
            interval: 5000 //changes the speed
        })
    </script>
</body>
</html>